# -*- coding: utf-8 -*-
"""Extra Credit Project: Artificial Neural Network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGMUZkvq_ag7BXESzBs1f8df8XbpmSWh

#**CBE-UY 4213 Extra-Credit Project: Artificial Neural Network**

Getting Started
1. Make a copy of this Google Colab document and save it to your Google Drive.
2. Download the required experimental data spreadsheet files found [here](https://drive.google.com/drive/folders/1ydst0-bYHfrC1ZI03HNrC5EY90m-_zm3?usp=sharing) and place them in a folder within your Google Drive.
3. To ensure that you are running Google Colab properly and to minimize any potential errors, run each code block in chronological order by pressing the "play" button located at the top left of each code block.
"""

import pandas as pd
from google.colab import drive
import torch

"""#GPU Setup
Utilizing a Graphics Processing Unit (GPU) yields faster computations, especially as more complex models are involved. This model utilizes a GPU to perform gradient calculations to learn from training data. The steps to change the device from CPU to GPU are outlined below:

1.  Select Runtime in the top left corner of Google Colab.
2.  In the dropdown menu, select "Change runtime type"
3.  Select "T4 GPU" and save.
4.  Press the "Connect T4" in the top right corner.
5.  Run the code block below. If successful, the program should print out "Using device: cuda".



"""

if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(f"Using device: {device}")

"""# Loading in the dataset
Rename the "file_path" in the code block so that it matches the file directory of your copy of the project files.
"""

drive.mount('/content/drive',force_remount=True)

file_path = '/content/drive/MyDrive/CO2 Gas Hydrate Model/File Dump/preprocessed_data.xlsx'       # IMPORTANT: RENAME HERE
df = pd.read_excel(file_path)
df.head()

"""# Artificial Neural Network
An artificial neural network (ANN) is a computational model, inspired by the human brain's structure, that utilizes multiple layers of neurons to learn from data in order to perform tasks such as pattern recognition and problem solving.     
  
  *(Optional): You can learn more about neural networks [here](https://www.youtube.com/watch?v=aircAruvnKk).*

    
      
    
  The first step in creating an ANN is to convert data into "tensors" for the model to learn. Run the following code block to convert the data into PyTorch tensors.
"""

import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
import seaborn as sns
import random

def set_seed(seed=0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # Enforce deterministic behavior
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.use_deterministic_algorithms(True)

set_seed(0)

# Load the data
X = df[['Time (s)', 'Pressure (MPa)', 'CO2 Flow Rate (mm3/s)', 'Subcooling (K)']]
y = df['Thickness (um)']

# Split data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=0)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=0)

# Normalize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Normalize the thickness
y_scaler = StandardScaler()
y_train = y_scaler.fit_transform(y_train.values.reshape(-1, 1))
y_val = y_scaler.transform(y_val.values.reshape(-1, 1))
y_test = y_scaler.transform(y_test.values.reshape(-1, 1))

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

"""Run the following code block to define and train the ANN."""

class SimpleANNWithDropout(nn.Module):
    def __init__(self, dropout_rate=0.2):
        super(SimpleANNWithDropout, self).__init__()
        self.fc1 = nn.Linear(X_train.shape[1], 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 64)
        self.fc4 = nn.Linear(64, 32)
        self.fc5 = nn.Linear(32, 1)

        # Dropout layers
        self.dropout = nn.Dropout(p=dropout_rate)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.dropout(x)
        x = torch.relu(self.fc2(x))
        x = self.dropout(x)
        x = torch.relu(self.fc3(x))
        x = self.dropout(x)
        x = torch.relu(self.fc4(x))
        x = self.dropout(x)
        x = self.fc5(x)  # Output layer without dropout
        return x

# Instantiate the model with dropout rate
model = SimpleANNWithDropout(dropout_rate=0.2)

# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training Loop
epochs = 1000
loss_values = []
for epoch in range(epochs):
    model.train()

    # Forward pass
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    # Backward propagation and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')
    loss_values.append(loss.detach().numpy())

epoch_values = np.linspace(0,len(loss_values),len(loss_values))
plt.plot(epoch_values,loss_values)
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Loss vs Epoch')
plt.show()

"""You have now successfully trained an ANN. Run the following code block to perform analysis on the performance of the ANN."""

# Evaluate on the validation set
model.eval()
with torch.no_grad():
    val_outputs = model(X_val_tensor)
    val_mse = mean_squared_error(y_val_tensor.numpy(), val_outputs.numpy())
    val_mae = mean_absolute_error(y_val_tensor.numpy(), val_outputs.numpy())
    val_r2 = r2_score(y_val_tensor.numpy(), val_outputs.numpy())

    print(f'Validation MSE: {val_mse:.4f}')
    print(f'Validation MAE: {val_mae:.4f}')
    print(f'Validation R²: {val_r2:.4f}')

# Evaluate on the test set
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_mse = mean_squared_error(y_test_tensor.numpy(), test_outputs.numpy())
    test_mae = mean_absolute_error(y_test_tensor.numpy(), test_outputs.numpy())
    test_r2 = r2_score(y_test_tensor.numpy(), test_outputs.numpy())

    print(f'Test MSE: {test_mse:.4f}')
    print(f'Test MAE: {test_mae:.4f}')
    print(f'Test R²: {test_r2:.4f}')

# Convert model output and target to numpy arrays
outputs_np = val_outputs.numpy()
y_val_np = y_val_tensor.numpy()

# Plot Expected vs Reality (Predicted vs Actual) for validation set
# plt.rcParams.update({
#     'font.size': 14,
#     'axes.titlesize': 18,
#     'axes.labelsize': 16,
#     'xtick.labelsize': 14,
#     'ytick.labelsize': 14
# })

plt.figure(figsize=(8, 6))
plt.scatter(y_val_np, outputs_np, color='blue', alpha=0.6)
plt.plot([min(y_val_np), max(y_val_np)], [min(y_val_np), max(y_val_np)], color='red', linestyle='--')  # Diagonal line
plt.title("Validation Set: Expected vs Reality (Predicted vs Actual)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.show()

# Plot Expected vs Reality (Predicted vs Actual) for test set

outputs_np_test = test_outputs.numpy()
y_test_np = y_test_tensor.numpy()

plt.figure(figsize=(8, 6))
plt.scatter(y_test_np, outputs_np_test, color='green', alpha=0.6)
plt.plot([min(y_test_np), max(y_test_np)], [min(y_test_np), max(y_test_np)], color='red', linestyle='--')  # Diagonal line
plt.title("Test Set: Expected vs Reality (Predicted vs Actual)")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.show()

# Fit Random Forest for feature importance
rf = RandomForestRegressor(n_estimators=300, random_state=0)
rf.fit(X_train, y_train)

# Random Forest Feature Importance
importances = rf.feature_importances_
feature_names = X.columns


plt.figure(figsize=(8, 5))
plt.barh(feature_names, importances, color="skyblue")
plt.title("Random Forest Feature Importance")
plt.xlabel("Importance")
plt.show()

# Permutation Importance
perm_importance = permutation_importance(rf, X_test, y_test, n_repeats=15, random_state=0)
perm_sorted_idx = perm_importance.importances_mean.argsort()

plt.figure(figsize=(8, 5))
plt.barh(np.array(feature_names)[perm_sorted_idx],
         perm_importance.importances_mean[perm_sorted_idx],
         color="lightgreen")
plt.title("Permutation Feature Importance")
plt.xlabel("Importance (mean decrease in score)")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(7, 5))
corr = df[['Time (s)', 'Pressure (MPa)', 'CO2 Flow Rate (mm3/s)', 'Subcooling (K)', 'Thickness (um)']].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", center=0)
plt.title("Correlation Heatmap")
plt.show()

"""# ANN Analysis
Now that you have a trained ANN, compare how the model predicts hydrate thickness to the actual known experimental data by running the code blocks below.

## Experiment A
"""

# Filter rows where Experiment == 'A'
df_a1 = df[df['Experiment'] == 'A1']
df_a2 = df[df['Experiment'] == 'A2']
df_a3 = df[df['Experiment'] == 'A3']

# Plot Experiments A
plt.scatter(df_a1['Time (s)'], df_a1['Thickness (um)'], label='Experiment A1', color='blue')
plt.scatter(df_a2['Time (s)'], df_a2['Thickness (um)'], label='Experiment A2', color='green')
plt.scatter(df_a3['Time (s)'], df_a3['Thickness (um)'], label='Experiment A3', color='red')

# Defining x variables
time_values = np.linspace(0, 300, 300).reshape(-1, 1)
pressure_fixed = np.full_like(time_values, 2.51)
co2_flow_fixed = np.full_like(time_values, 1.67)
subcooling_fixed = np.full_like(time_values, 0.5)

# Combine into a full feature array
X_custom = np.hstack([time_values, pressure_fixed, co2_flow_fixed, subcooling_fixed])

# Normalize using the same scaler as training
X_custom_scaled = scaler.transform(X_custom)

# Convert to PyTorch tensor
X_custom_tensor = torch.tensor(X_custom_scaled, dtype=torch.float32)

# Model prediction
model.eval()
with torch.no_grad():
    y_pred_scaled = model(X_custom_tensor).numpy()

# Inverse transform predictions to real thickness (µm)
y_pred_real = y_scaler.inverse_transform(y_pred_scaled)

# Plot
plt.plot(time_values, y_pred_real, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=1.67 mm³/s, Subcooling=0.5 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

file_path_2 = '/content/drive/MyDrive/CO2 Gas Hydrate Model/File Dump/data_averages.xlsx'  # IMPORTANT: RENAME HERE
df_avg = pd.read_excel(file_path_2)

# Evaluate on average A
time_values_2 = df.iloc[0:59,1].to_numpy().reshape(-1, 1)
pressure_fixed_2 = np.full_like(time_values_2, 2.51)
co2_flow_fixed_2 = np.full_like(time_values_2, 1.67)
subcooling_fixed_2 = np.full_like(time_values_2, 0.5)
X_custom_2 = np.hstack([time_values_2, pressure_fixed_2, co2_flow_fixed_2, subcooling_fixed_2])
X_custom_scaled_2 = scaler.transform(X_custom_2)
X_custom_tensor_2 = torch.tensor(X_custom_scaled_2, dtype=torch.float32)
model.eval()
with torch.no_grad():
    y_pred_scaled_2 = model(X_custom_tensor_2).numpy()

y_pred_real_2 = y_scaler.inverse_transform(y_pred_scaled_2)
r2 = r2_score(df_avg['A'],y_pred_real_2)
print(r2)

plt.figure
plt.scatter(df_a1['Time (s)'], df_avg['A'], label='Average A', color='blue')
plt.plot(time_values_2, y_pred_real_2, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('ANN Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=1.67 mm³/s, Subcooling=0.5 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""## Experiment B"""

# Filter rows
df_b1 = df[df['Experiment'] == 'B1']
df_b2 = df[df['Experiment'] == 'B2']
df_b3 = df[df['Experiment'] == 'B3']

# Plot for Experiment B
plt.scatter(df_b1['Time (s)'], df_b1['Thickness (um)'], label='Experiment B1', color='blue')
plt.scatter(df_b2['Time (s)'], df_b2['Thickness (um)'], label='Experiment B2', color='green')
plt.scatter(df_b3['Time (s)'], df_b3['Thickness (um)'], label='Experiment B3', color='red')

# 1. Create input: Time from 0 to 300, rest are fixed
time_values = np.linspace(0, 300, 300).reshape(-1, 1)
pressure_fixed = np.full_like(time_values, 2.51)
co2_flow_fixed = np.full_like(time_values, 1.67)
subcooling_fixed = np.full_like(time_values, 1)

# 2. Combine into a full feature array
X_custom = np.hstack([time_values, pressure_fixed, co2_flow_fixed, subcooling_fixed])

# 3. Normalize using the same scaler as training
X_custom_scaled = scaler.transform(X_custom)

# 4. Convert to PyTorch tensor
X_custom_tensor = torch.tensor(X_custom_scaled, dtype=torch.float32)

# 5. Model prediction
model.eval()
with torch.no_grad():
    y_pred_scaled = model(X_custom_tensor).numpy()

# 6. Inverse transform predictions to real thickness (µm)
y_pred_real = y_scaler.inverse_transform(y_pred_scaled)

# 7. Plot
plt.plot(time_values, y_pred_real, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=1.67 mm³/s, Subcooling=1 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

file_path_2 = '/content/drive/MyDrive/CO2 Gas Hydrate Model/File Dump/data_averages.xlsx' # IMPORTANT: RENAME HERE
df_avg = pd.read_excel(file_path_2)

time_values_2 = df.iloc[0:59,1].to_numpy().reshape(-1, 1)
pressure_fixed_2 = np.full_like(time_values_2, 2.51)
co2_flow_fixed_2 = np.full_like(time_values_2, 1.67)
subcooling_fixed_2 = np.full_like(time_values_2, 1)
X_custom_2 = np.hstack([time_values_2, pressure_fixed_2, co2_flow_fixed_2, subcooling_fixed_2])
X_custom_scaled_2 = scaler.transform(X_custom_2)
X_custom_tensor_2 = torch.tensor(X_custom_scaled_2, dtype=torch.float32)
model.eval()
with torch.no_grad():
    y_pred_scaled_2 = model(X_custom_tensor_2).numpy()

y_pred_real_2 = y_scaler.inverse_transform(y_pred_scaled_2)
r2 = r2_score(df_avg['B'],y_pred_real_2)
print(r2)

plt.figure
plt.scatter(df_b1['Time (s)'], df_avg['B'], label='Average B', color='blue')
plt.plot(time_values_2, y_pred_real_2, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('ANN Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=1.67 mm³/s, Subcooling=1 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""## Experiment C"""

# Filter rows
df_b1 = df[df['Experiment'] == 'C1']
df_b2 = df[df['Experiment'] == 'C2']
df_b3 = df[df['Experiment'] == 'C3']

# Plot for Experiment C
plt.scatter(df_b1['Time (s)'], df_b1['Thickness (um)'], label='Experiment C1', color='blue')
plt.scatter(df_b2['Time (s)'], df_b2['Thickness (um)'], label='Experiment C2', color='green')
plt.scatter(df_b3['Time (s)'], df_b3['Thickness (um)'], label='Experiment C3', color='red')

# 1. Create input: Time from 0 to 300, rest are fixed
time_values = np.linspace(0, 300, 300).reshape(-1, 1)
pressure_fixed = np.full_like(time_values, 2.51)
co2_flow_fixed = np.full_like(time_values, 1.67)
subcooling_fixed = np.full_like(time_values, 1.5)

# 2. Combine into a full feature array
X_custom = np.hstack([time_values, pressure_fixed, co2_flow_fixed, subcooling_fixed])

# 3. Normalize using the same scaler as training
X_custom_scaled = scaler.transform(X_custom)

# 4. Convert to PyTorch tensor
X_custom_tensor = torch.tensor(X_custom_scaled, dtype=torch.float32)

# 5. Model prediction
model.eval()
with torch.no_grad():
    y_pred_scaled = model(X_custom_tensor).numpy()

# 6. Inverse transform predictions to real thickness (µm)
y_pred_real = y_scaler.inverse_transform(y_pred_scaled)

# 7. Plot
plt.plot(time_values, y_pred_real, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=1.67 mm³/s, Subcooling=1.5 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

file_path_2 = '/content/drive/MyDrive/CO2 Gas Hydrate Model/File Dump/data_averages.xlsx' # IMPORTANT: RENAME HERE
df_avg = pd.read_excel(file_path_2)

time_values_2 = df.iloc[0:59,1].to_numpy().reshape(-1, 1)
pressure_fixed_2 = np.full_like(time_values_2, 2.51)
co2_flow_fixed_2 = np.full_like(time_values_2, 1.67)
subcooling_fixed_2 = np.full_like(time_values_2, 1.5)
X_custom_2 = np.hstack([time_values_2, pressure_fixed_2, co2_flow_fixed_2, subcooling_fixed_2])
X_custom_scaled_2 = scaler.transform(X_custom_2)
X_custom_tensor_2 = torch.tensor(X_custom_scaled_2, dtype=torch.float32)
model.eval()
with torch.no_grad():
    y_pred_scaled_2 = model(X_custom_tensor_2).numpy()

y_pred_real_2 = y_scaler.inverse_transform(y_pred_scaled_2)
r2 = r2_score(df_avg['C'],y_pred_real_2)
print(r2)

plt.figure
plt.scatter(df_b1['Time (s)'], df_avg['C'], label='Average C', color='blue')
plt.plot(time_values_2, y_pred_real_2, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('ANN Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=1.67 mm³/s, Subcooling=1.5 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""## Experiment D"""

# Filter rows
df_b1 = df[df['Experiment'] == 'D1']
df_b2 = df[df['Experiment'] == 'D2']
df_b3 = df[df['Experiment'] == 'D3']

# Plot for Experiment B
plt.scatter(df_b1['Time (s)'], df_b1['Thickness (um)'], label='Experiment D1', color='blue')
plt.scatter(df_b2['Time (s)'], df_b2['Thickness (um)'], label='Experiment D2', color='green')
plt.scatter(df_b3['Time (s)'], df_b3['Thickness (um)'], label='Experiment D3', color='red')

# 1. Create input: Time from 0 to 300, rest are fixed
time_values = np.linspace(0, 300, 300).reshape(-1, 1)
pressure_fixed = np.full_like(time_values, 2.51)
co2_flow_fixed = np.full_like(time_values, 0.167)
subcooling_fixed = np.full_like(time_values, 0.5)

# 2. Combine into a full feature array
X_custom = np.hstack([time_values, pressure_fixed, co2_flow_fixed, subcooling_fixed])

# 3. Normalize using the same scaler as training
X_custom_scaled = scaler.transform(X_custom)

# 4. Convert to PyTorch tensor
X_custom_tensor = torch.tensor(X_custom_scaled, dtype=torch.float32)

# 5. Model prediction
model.eval()
with torch.no_grad():
    y_pred_scaled = model(X_custom_tensor).numpy()

# 6. Inverse transform predictions to real thickness (µm)
y_pred_real = y_scaler.inverse_transform(y_pred_scaled)

# 7. Plot
plt.plot(time_values, y_pred_real, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('ANN Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=0.167 mm³/s, Subcooling=0.5 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

file_path_2 = '/content/drive/MyDrive/CO2 Gas Hydrate Model/File Dump/data_averages.xlsx' # IMPORTANT: RENAME HERE
df_avg = pd.read_excel(file_path_2)

time_values_2 = df.iloc[0:59,1].to_numpy().reshape(-1, 1)
pressure_fixed_2 = np.full_like(time_values_2, 2.51)
co2_flow_fixed_2 = np.full_like(time_values_2, 0.167)
subcooling_fixed_2 = np.full_like(time_values_2, 0.5)
X_custom_2 = np.hstack([time_values_2, pressure_fixed_2, co2_flow_fixed_2, subcooling_fixed_2])
X_custom_scaled_2 = scaler.transform(X_custom_2)
X_custom_tensor_2 = torch.tensor(X_custom_scaled_2, dtype=torch.float32)
model.eval()
with torch.no_grad():
    y_pred_scaled_2 = model(X_custom_tensor_2).numpy()

y_pred_real_2 = y_scaler.inverse_transform(y_pred_scaled_2)
r2 = r2_score(df_avg['D'],y_pred_real_2)
print(r2)

plt.figure
plt.scatter(df_b1['Time (s)'], df_avg['D'], label='Average D', color='blue')
plt.plot(time_values_2, y_pred_real_2, color='orange', label='Predicted Thickness')
plt.xlabel('Time (s)')
plt.ylabel('Predicted Thickness (µm)')
plt.title('Predicted Hydrate Thickness vs Time\n(Pressure=2.51 MPa, CO₂ Flow=0.167 mm³/s, Subcooling=0.5 K)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()